### ISSUE TITLE
Shows that the update is available while it's not

### ISSUE THREAD

**Issue by stanol** [sergi0g/cup#10]
```
root@DietPi:~# docker run -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/sergi0g/cup check
lcdp/docker-curl-cron:latest                                    Update available
lscr.io/linuxserver/changedetection.io:latest                         Up to date
lscr.io/linuxserver/qbittorrent:latest                                Up to date
ghcr.io/jellyfin/jellyfin-vue:unstable                                Up to date
ghcr.io/netdata/netdata:stable                                        Up to date
ghcr.io/sergi0g/cup:latest                                            Up to date
ghcr.io/home-assistant/home-assistant:stable                          Up to date
ghcr.io/fmartinou/whats-up-docker:latest                              Up to date
amir20/dozzle:latest                                                  Up to date
glanceapp/glance:latest                                               Up to date
portainer/portainer-ee:latest                                         Up to date
adguard/adguardhome:latest                                            Up to date
twinproduction/gatus:latest                                           Up to date
kopia/kopia:latest                                                    Up to date
jellyfin/jellyfin:latest                                              Up to date
productiveops/dokemon:latest                                          Up to date
louislam/dockge:1                                                     Up to date
eclipse-mosquitto:latest                                              Up to date
containrrr/watchtower:latest                                          Up to date
cloudflare/cloudflared:latest                                         Up to date

root@DietPi:~# docker pull lcdp/docker-curl-cron:latest
latest: Pulling from lcdp/docker-curl-cron
Digest: sha256:7b7464829a28bb18e40782beaae99faab4d035115f6f47906dce56786e40f156
Status: Image is up to date for lcdp/docker-curl-cron:latest
docker.io/lcdp/docker-curl-cron:latest

```

**Comment by sergi0g** [comment]
Hello @stanol! Thank you very much for reporting this bug. I apologize for the incorrect results.

I am not sure why, but Docker Hub seems to not respect the `Content-Type` header Cup sets when making a request. Cup asks for `application/vnd.docker.distribution.manifest.v2.list+json`, but Docker Hub responds with `application/vnd.docker.distribution.manifest.v1+prettyjws` for the particular image you are trying to pull, which results in Cup incorrectly saying it has an update available.

This probably cannot be fixed on Cup's side, unless a different method of retrieving the latest digest is found. I am very sorry.

**Comment by sergi0g** [comment]
It seems the image you're using is unmaintained (last updated 4 years ago) and was built with an old version of Docker that used old manifests which are incompatible with Cup. I'd suggest using another image (many are available) which is properly maintained.
I am closing this issue as it will not be fixed.

**Comment by stanol** [comment]
Same situation with the other image. This one is not old. https://hub.docker.com/r/kakshipth/gomanagedocker

**Comment by sergi0g** [comment]
@stanol this one is indeed not old, however it still uses the old manifest which indicates that the developer is using an old version of Docker to build the image. It looks like they're trying to set up an automation to build with Github Actions and if that succeeds, it should be able to work well with Cup.

**Comment by sergi0g** [comment]
@stanol I feel very embarrassed saying this, but I was wrong. It seems that in some cases (I suspect for single-arch images), the registry gives Cup a wrong manifest because it thinks Cup is an old Docker client.

I was testing Cup with a local registry and in the logs I saw: `rewriting manifest sha256:867b634a776a0179d1ed10e5896f475c07fe4805d711600de0644277760dff5d in schema1 format to support old client`. I dug into the registry's code and found that this happens when I don't send an `Accept: application/vnd.docker.distribution.manifest.v2+json` header.

It seems that in some cases (I suspect for single-arch images), the registry gives Cup a wrong manifest because it thinks Cup is an old Docker client, since that header isn't set. Your images are fine! The registry takes care of converting between formats. I will fix this ASAP and I am very, very sorry for this problem. Please forgive me.
