### ISSUE TITLE
Does not work if any insecure registry used.

### ISSUE THREAD

**Issue by jd0000** [sergi0g/cup#12]
I have a local registry for a few images, and for various reasons it is 'insecure' - uses http. My docker daemon.json file has it included in insecure-registries, and it works fine. However, cup tries to connect to https, and fails completely, without providing info on the majority of images which are using standard secure external registries.
```
~/docker > docker run -v /var/run/docker.sock:/var/run/docker.sock -t ghcr.io/sergi0g/cup serve
https://my_local_registry:5000/v2/: Connection Failed: tls connection init failed: received corrupt message of type InvalidContentType
```

**Comment by sergi0g** [comment]
Hello @jd0000! Thanks for opening this issue. I don't think I will add support for insecure registries in the future. However, error handling will be improved so it shows as unknown. I hope to push an update in a few days.

In the meantime, please consider enabling HTTPS on your local registry, as it is more secure anyway.

Thanks again for opening this issue!

**Comment by sergi0g** [comment]
@jd0000 the latest release adds support for insecure registries. Update Cup and check out the docs to set it up!
