### ISSUE TITLE
[FR] Timezone support

### ISSUE THREAD

**Issue by agrmohit** [sergi0g/cup#17]
Support for timezone would be great. Right now the only place where this seems relevant is the last checked time in the server UI which currently shows last refreshed time in UTC.

For docker installations, a good approach might be using `TZ` environment variable like [LinuxServer.io's images](https://docs.linuxserver.io/images/docker-adguardhome-sync/#docker-compose-recommended-click-here-for-more-info).

I don't see myself visiting the UI very often (despite it looking great) because of the [homepage widget](https://github.com/sergi0g/cup/discussions/16) so it could be considered low priority.

Thanks for building this.

**Comment by sergi0g** [comment]
Including timezone data does increase the binary size, but I'll add this to the roadmap. Thanks!

**Comment by sergi0g** [comment]
@agrmohit I'm closing this as the latest release shows the relative time instead!
