### ISSUE TITLE
[BUG] Documentation site logo results in 404

### ISSUE THREAD

**Issue by ioverho** [sergi0g/cup#27]
Clicking the documentation site's top left logo navigates to `https://sergi0g.github.io/cup/.../sergi0g.github.io/cup` where `...` is `installation` or `usage`, etc.

The current landing page `https://sergi0g.github.io/cup/` also returns a 404.

**Comment by sergi0g** [comment]
Hi @ioverho!

Thanks for reporting this bug! I am generally having trouble with 404s at the moment.

> Clicking the documentation site's top left logo navigates to `https://sergi0g.github.io/cup/.../sergi0g.github.io/cup` where `...` is `installation` or `usage`, etc.

I can confirm this occurs and I'll try to debug it!

> The current landing page `https://sergi0g.github.io/cup/` also returns a 404.

Where is this link? Everywhere in Github I link to https://sergi0g.github.io/cup/docs/.

**Comment by sergi0g** [comment]
@ioverho I fixed it!
