### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Its4Nik** [sergi0g/cup#29]
When trying to gather statistics for my own project from cup i get a CORS error:

```Text
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cup.XXXXXX.de/json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Error fetching data: TypeError: NetworkError when attempting to fetch resource. CupIntegration.js:22:24
```

And I didn't see any variable or settings to allow CORS

**Comment by sergi0g** [comment]
That isn't related to Cup, but to how you configure your project. You will either need to set the required headers on your frontend, or call the API entirely from the backend.
