### ISSUE TITLE
[FR] Add support Homepage

### ISSUE THREAD

**Issue by John710** [sergi0g/cup#38]
Are you planning to add a widget of your service to the dashboard [Homepage](https://github.com/gethomepage/homepage)?

**Comment by John710** [comment]
I'm sorry, for some reason I didn't notice that it already exists. But for some reason there is no official support.

**Comment by sergi0g** [comment]
Hi @John710,
I was planning on doing this after an API redesign I've planned, so nothing breaks.

If you still want an official Homepage widget, you can request one [here](https://github.com/gethomepage/homepage/discussions/new?category=feature-requests).  If you get enough upvotes, it will be created.

I'm closing this issue now, as there's nothing else I can do.
