### ISSUE TITLE
Theme switcher button

### ISSUE THREAD

**Issue by steveiliop56** [sergi0g/cup#4]
Hello,

Awesome project! My only tiny issue is that I would like to have a theme switcher button to change to light mode/dark mode because... Why not lol

**Comment by sergi0g** [comment]
Hey @steveiliop56! Thanks a lot for your feedback!

I've actually considered this idea before and I decided not to implement it for the following reasons:
- The web UI is just plain HTML and I would like to keep it like that. Adding Javascript to control theming would make the code messy.
- Most people will never need this feature: People generally pick a light or dark theme for their entire system. It is uncommon for somebody to choose a dark theme (for example) only for a specific webpage.
- I actually have no idea where to position it on the page. I think it would ruin the design.

Unless I switch to a framework, or at least find a good place to put the switcher, this will not be implemented. In the meantime, if you really feel the need to use a different theme, you can use an extension like [Dark Reader](https://darkreader.org/).

**Comment by steveiliop56** [comment]
Hello @sergi0g,

Thank you for the detailed explanation, I had a look in your code and yeahh adding a button would be hard and a bit unnecessary. Closing this issue...
