### ISSUE TITLE
[BUG] Does not inform about the new version

### ISSUE THREAD

**Issue by John710** [sergi0g/cup#41]
![2024-10-22_22-48-22](https://github.com/user-attachments/assets/1f6f6d38-25d9-4cac-b706-cd0d66786b35)
As an example, I had CUP version 2.3.1 installed, but it did not inform me that version 2.4.0 had already been released.

**Comment by sergi0g** [comment]
Hi @John710! This is not a bug. Cup is working as intended here. Cup checks for new _digests_ for a specific _tag_ you've already pulled and not for new _tags_. In the future, this will also be supported. I'm closing this issue now.
