### ISSUE TITLE
[FR] Add manual docker image

### ISSUE THREAD

**Issue by dennisfrijlink** [sergi0g/cup#44]
It would be nice to have to possibility to add a url of a docker image manually, so I can track updates of containers running on other machines.

**Comment by sergi0g** [comment]
Hi @dennisfrijlink!

In an update coming soom you'll be able to run Cup "agents" on multiple servers and access them all through 1 dashboard. This should cover your use case. I'm closing this issue now. Feel free to reopen it if you disagree.
