### ISSUE TITLE
[Suggestion] Order list by Up to date | Updates available | Unknown

### ISSUE THREAD

**Issue by Laflamme** [sergi0g/cup#5]
Thank you for your wonderful project! I am new to homelabing, and have very limited coding skills, so please allow me to make a suggestion.

I believe it would make sense for the image list to be ordered by categories (Up to date | Updates available | Unknown). 

The statistics at the top of the page could serve as links to corresponding parts of the list, and you could even match the statistic text (or background) colors with the icons in the list.

**Comment by sergi0g** [comment]
Hi @Laflamme! I'm glad you liked this project!

I will definitely implement filtering! It isn't hard, just something I keep putting off 😂. I don't think the list could get long enough to require linking to different parts of it, but it could be considered. Even on my desktop, where I pull new images all the time (I currently have about 90), the list isn't too long to scroll.


Finally, can you please clarify what you mean here? I wasn't able to understand. I'm sorry!

> you could even math the statistic text (or background) colors with the icons in the list.

**Comment by Laflamme** [comment]
Sorry, it was a typo, I meant "**match** the statistic text (or background) colors with the icons in the list", so "Up to date <number>" in green, "Updates available <number>" in blue, etc.

**Comment by sergi0g** [comment]
Oh I understand now. I'm not sure adding color there would look very nice, but what I definitely can do is add the icons used in the list to their respective statistic (with color of course). I'll just need to find an icon for the "Monitored images". If you want to, please take a look at https://tabler.io/icons and tell me if you have any ideas for an icon.

**Comment by sergi0g** [comment]
Cool, thanks!

**Comment by sergi0g** [comment]
Hey @Laflamme! I'm working on the icons you suggested. Here's a preview:

![Screen Shot 2024-07-13 at 11 12 23](https://github.com/user-attachments/assets/5ba81bdd-b3d0-444a-b408-48b666f2f3c1)
![Screen Shot 2024-07-13 at 11 12 17](https://github.com/user-attachments/assets/bdb5cefc-488c-4726-b32a-53bcee51e044)
![Screenshot from 2024-07-13 11-11-44](https://github.com/user-attachments/assets/1273b461-23a8-4de9-9f8c-a1e73b8c99c3)
![Screenshot from 2024-07-13 11-12-00](https://github.com/user-attachments/assets/82de46d7-d613-4b1f-aa31-aa62cbac39dd)


How does that look? (By the way, I will sort the list later, just testing for now :smile:)

**Comment by Laflamme** [comment]
Looks great! 

It looks best when there is at least two columns, otherwise there is a lot of white space between the text and the icons, which can make them feel a little bit disconnected. Also, single column makes the box look just a little bit too much like an item from the image list in my opinion.

Considering it’s only one or two words per box, I think you could afford to keep four and two column layouts on narrower viewports (two columns on your first image, four on the second one).

My instinct would be to have a different color for each of the four icons: blue for Images monitored, green for Up to date, yellow for update available, and you could keep Unknown as grey (as long as Images monitored doesn’t stay black), or change it to orange or red, for instance.

**Comment by sergi0g** [comment]
If you ask me it looks a little squished this way:
![Screen Shot 2024-07-13 at 15 15 54](https://github.com/user-attachments/assets/3ad98604-07f9-4de5-bc98-cd9bff7ba8c7)

Single column mode looks fine to me on my phone. What do you think?

Yellow could be used for update available, although it implies a sense of urgency. Blue is more calming. If I add semver support (checking if an update is major, minor or patch), I'd use red for major updates, yellow for minor and blue for patch. I don't know if that makes sense to you. Also yellow doesn't look very good on the blueish background.

**Comment by Laflamme** [comment]
Ohhhh! Your semver color coding idea sounds awesome, definitely go for that (and I think you should use it to further define the list order once that's implemented)! Maybe with a tooltip appearing above the icon to explain the color code on click/hover.

The two column layout doesn't seem too squished to me. The content of each box seems to be spaced about the same as in your 4 column layout on larger viewports. One thing you could do is move the icon to the lower right of the box, to give more space to the text (less space is needed next to the number; I doubt there are a lot of users with more than 999999 docker images 😅).

The more compact statistic boxes allow for more docker images to appear on screen when you load the page, which feels better balanced to me (1/3 header, 2/3 content, vs less than half the screen for content otherwise).

What do you think?

**Comment by sergi0g** [comment]
> Maybe with a tooltip appearing above the icon to explain the color code on click/hover.
This is already on the roadmap.

> One thing you could do is move the icon to the lower right of the box, to give more space to the text
Noted.

OK, you convinced me 😂. I'll switch to 2 columns on small screens.
