### ISSUE TITLE
[SUGGESTION] Add fields for count of monitored, updated, available to json

### ISSUE THREAD

**Issue by RichyHBM** [sergi0g/cup#8]
As per the title, the /json api should also include properties for the amount of images monitored, out of date, and up to date

**Comment by RichyHBM** [comment]
Awesome! Thanks, it will make adding a widget for homepage locally much easier without the need to manage my own fork 😁

**Comment by sergi0g** [comment]
Oh so this was for Homepage? If you make a widget, I'd suggest getting in touch with the project to include it, so everybody can benefit from your work! As a bonus, it'll be mentioned in the docs too! (I hope I convinced you 😉)

**Comment by RichyHBM** [comment]
Hey, yea I had thought of it but they now require a minimum of 10 requests before allowing a widget to be integrated (which is fair if they are going to be maintaining it) They have also added a custom api widget since I last did work on homepage widgets, which would allow using CUPS with this change without the need for a specific cups widget

I did have one query/suggestion based on the change, currenly the metrics are an array with `name=metric, value=the value`. Was there a particular reason for doing it this way? I'm just thinking if it would be easier when using the data for it to just be `metric=value` directly?

So, from
```"metrics": [{"name": "Monitored images", "value": self.json["metrics"]["monitored_images"].as_usize()}, {"name": "Up to date", "value": self.json["metrics"]["up_to_date"].as_usize()}, {"name": "Updates available", "value": self.json["metrics"]["update_available"].as_usize()}, {"name": "Unknown", "value": self.json["metrics"]["unknown"].as_usize()}],```

to:
```"metrics": {"monitored_images": self.json["metrics"]["monitored_images"].as_usize(), "up_to_date": self.json["metrics"]["up_to_date"].as_usize(), "update_available": self.json["metrics"]["update_available"].as_usize(), "unknown": self.json["metrics"]["unknown"].as_usize()},```

I'm not familiar with rust, so take that syntax with a pinch of salt

**Comment by RichyHBM** [comment]
For anyone coming across this in the future, these are the docker labels to use for this to work as a homepage widget
```
      - homepage.widget.type=customapi
      - homepage.widget.url=http://cup:8000/json
      - homepage.widget.refreshInterval=10000
      - homepage.widget.method=GET
      - homepage.widget.mappings[0].field.metrics=monitored_images
      - homepage.widget.mappings[0].label=Monitored images
      - homepage.widget.mappings[0].format=number
      - homepage.widget.mappings[1].field.metrics=up_to_date
      - homepage.widget.mappings[1].label=Up to date
      - homepage.widget.mappings[1].format=number
      - homepage.widget.mappings[2].field.metrics=update_available
      - homepage.widget.mappings[2].label=Updates available
      - homepage.widget.mappings[2].format=number
      - homepage.widget.mappings[3].field.metrics=unknown
      - homepage.widget.mappings[3].label=Unknown
      - homepage.widget.mappings[3].format=number
      ```
